#+TITLE: Caracterizarea personajului Felix
#+AUTHOR: Babin Ion
#+LANGUAGE: ro
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="imagine.css" />
#+OPTIONS: num:nil html-style:nil

* Caracterizarea personajului Felix din romanul Engigma Otiliei
Felix este protagonistul romanului Enigma Otiliei. Spre diferență de restul personajelor, acesta nu reprezintă o tipologie umană, ci un amestec din acestea. Romanul descrie progresia acestuia, dintr-un adolescent naiv, într-o persoană completă, atât pe plan profesional (își atinge scopul și ajunge medic), cât și pe plan personal. Felix este singurul exemplu pozitiv - singurul personaj ambițios și nepasionat de bani. Antiteza cu celelalte personaje accentuează doar vanitatea acestora, ele reprezentând doar niște nulități atunci când sunt comparate chiar și cu un tânăr inocent și lipsit de experiență ca Felix.

Caracterizarea directă de la începutul romanului îl descriu ca pe o persoană slabă și plăpândă: „fața îi era juvenilă și prelungă, aproape feminină”, caracterizare care vine să accentueze, prin antiteză, cât de mult progresează acesta spre sfârșitul romanului. Portretul fizic al acestuia devine astfel o fereastră spre portretul moral al acestuia.

Desigur, punerea persoanjului într-o situație dificilă este cel mai bun mod de a vedea din ce e făcut acesta. Încercarea la care este pus Felix - iubirea neîmpărtășită a Otiliei nu îl doboară, ci îl motivează să-și atingă scopurile - dând astfel dovadă de caracterul unui stoic.
