#+TITLE: Limba si literatura română
#+AUTHOR: Babin Ion
#+LANGUAGE: ro
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="imagine.css" />
#+OPTIONS: num:nil html-style:nil

* Teme
** [[id:74308168-3d97-4e18-83e1-4593fce406cb][Romantism]]
*** [[id:eed50282-1a1e-4461-93fc-b5187d735312][Cântare României]]
*** [[id:e8fc70fa-1720-494b-a845-b918544401e5][Floare albastră]]
*** [[id:e77e7ca0-9997-48d7-9bb9-0cae83a21ac0][Luceafarul]]
** [[id:f5c196be-604f-4eb8-8bfc-c1b65adfb543][Scrierea funcțională]]
*** [[id:e6787e56-b1dd-4c90-a051-e998aeaccced][Procura și Invitația]]
** [[id:7a6b40ad-f1ea-4426-9f76-61975c77ef9e][Realism]]
* Articles
** [[id:90c0f9d7-fed0-4c68-b730-78af107ce2bc][On writing better essays]]

* Essays
** on Patriotism
* Atelier de scriere
** Perioada interbelică a literaturii romane a fost destul de rodnică, căci a oferit câteva romane foarte importante pentru proza realistă de la noi. Un roman realist care valorifică tematica rurală este și romanul „Ion”, care a apărut în 1920, revoluționând proza noastră.
** Nucleul romanului îl constituie cele două nuvele („Zestrea” și „Rușinea”). Mai multe evenimente, scene din viața reală au servit drept surse de inspirație pentru autor. De exemplu, scena în care un țăran își sărută glia, de parcă și-ar săruta iubita a fost văzută chiar de autor; Personajul central este construit după un model pe care autorul l-a întâlnit în viața reală și pe care îl chema Ion al Glanetașului. O altă sursă de inspirație l-a servit istoria dramatică a unei fete rămasă însărcinată cu un țăran sărac pe care i-a povestit-o chiar sora autorului. Realitățile satului ardelenesc de la începutul secolului al XX-lea, au servit, de asemenea, drept sursă de inspirație.
** Fiind un roman realist, perspectiva narativă este obiectivă, nararea se face la persoana a III-a, cu un narator omniscient.
** Personajul central, Ion, este un personaj eponim, deci prenumele lui va deveni titlul operei.
** Romanul are două părți: /Glasul Pământului/ și /Glasul Iubirii/, iar fiecare parte - mai multe capitole.
** Acțiunea desfășoară pe 2 planuri: un plan narativ urmărește evoluția personajului Ion, iar al doilea prezintă viața satului Pripas.
** Metafora „Glasul” din titlurile celor două părți semnifică cele două pasiuni (Pământul și Iubirea), care și l-au distrus pe Ion.
** Romanul e construit prin intermediul inelului compozițional, căci se deschide/începe prin descrierea drumului ce duce spre satul Pripas, un sat românesc din Ardeal, iar în final motivul drumului este prezent, numai că e vorba de drumul ce iese din sat. Motivul drumului are mai multe conotații: drumul vieții, drumul parcurs de cititor, care îi va aduce o bogată experiență de viață. Tot de inelul compozițional ține și scena horei, pe care o găsim în debutul romanului, dar și la final. Simbolistica acestui dans popular este destul de amplă, și include mai multe semnificații: cercul vieții(o generație trece, alta vine), și ideea de egalitate, și ideea de unitate
*** În roman sunt valorificate mai multe tehnnici narative. Merită analizate mai profund 2 dintre ele:
1. Tehnica planurilor narative. Presupune împletirea celor două linii de subiect, și anume viața țăranilor și viața intelectualității sătești. Perosajul Ion este construit prin tehnica basoreliefului, căci acesta domină celelalte personaje ale romanului.
2. Tehnica contrapunctului. Personajul Ion este prezentat în contrast cu George. Destinele ambelor vor fi dramatice: Ion se însoară cu Ana doar poentru zestrea ei, iar George se va însura cu Florica - femeia pe care o iubea nebunește Ion.
** Cronotopul romanului îl putem stabili ușor: acțiunea generală a romanului are loc la începutul secolului 20, în satul Pripas. Romanul începe cu o zi de duminică, în care toți locuitorii se strâng la hora satului, în curtea unei văduve.
** În linii mari romanul abordează conflictul tragic dintre om și dorința acestuia de a deține cât mai mult pământ. În umbra conflictului central stă un alt conflict și anume cel dintre Ion și înstăritul țăran George.
** După cum menționează și George Călinescu: „Toți flăcăii din sat sunt varietăți de Ion”. Personajul Ion este un personaj rotund deoarece romanul ne permite să-l cunoaștem din mai multe perspective: și psihologic, și social. Personajul Ion are statutul și de personaj eponim căci prenumele său devine tutlu de operă. Autorul va folosi în construirea acestui personaj câteva tehnici originale. De exemplu prin tehnica basoreliefului autorul va scoate în prim plan personalitatea lui Ion, iar celelalte personaje vor sta în umbra lui. Prin tehnica contrapunctului prozatorul va scoate la lumină relația tensionată între Ion și George. Tipologia umană pe care o reprezintă acest persoaj este tipul arivistului(parvenitului).
** Dacă la început de roman Ion pare a fi un tânăr plăcut, harnic, ambițios, apoi încet, încet cele două pasiuni(pământul și iubirea) îl dezumanizează. În operă personajul central va fi caracterizat direct de căre narator, de către alte personaje, dar foarte importantă devine caracterizarea indirectă. Cititorul îi poate înțelege psihologia prin fapte, prin limbaj, prin comportament.
** Personajul Ion este unul contradictoriu și din perspectiva că îmbină viclenia cu naivitatea sau gingășia cu brutalitatea. El începe să devină antipatic pentru cititor atunci când o seduce pe Ana doar pentru a pune stăpânire pe zestrea frumușică a acesteia. La finele romanului cititorul îi va afla adevărata esență al lui Ion, căci mai multe vieți și destine curmate vor fi pe conștiința lui.
** În final, nu fără tristețe menționăm că parvenitismul este o tipologie prea des întâlnită și în prezent. Odată cu transformarea societății în una consumerstică, a avut loc o transformare și o înlesnire în ceea ce privește metodele de propagare ale parvenitismului. O situație materială favorabilă astăzi este, fără îndoială, una din condițiile esențiale pentru dezvoltarea unui om, așa cum a fost cu câteva secole în urmă. Este important, însă, să existe astfel de romane, care să critice materialismul dus la absurd, și să-i arate adevărata față - de cele mai multe ori cu final tragic. În caz contrar - sentimentele pure și lucrurile care contează cu adevărat riscă să fie înlocuite de plăceri temporare și deșarte.
