#+TITLE: Resurse
#+AUTHOR: Babin Ion
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../imagine.css" />
#+OPTIONS: num:nil toc:nil html-style:nil

* Resursele din care eu învăț
Când vine vorba de învățare, eu sunt genul de persoană care a) ușor se plictisește și b) preferă cărțile cursurilor video. De asta eu învăț din mai multe cărți și resurse deodată. M-am plictisit de una? Învăț din alta.

** Programare
*** Colegiu
Pentru Java am cărțile /Think Java/, /Core Java/, /Effective Java/, /OCA Java SE8/, /Modern Java In Action/, și /Design Patterns (Gang of Four)/. Cu toate acestea, eu cred că cel mai bine înveți atunci când lucrezi la un proiect, cu minimul de cunoștințe. De aceea, nu citesc cărțile cap-coadă, ci le folosesc ca referințe pentru a-mi adânci cunoștințele obținute de pe stackoverflow și indienii youtube-ului.

*** Restul
În timpul liber, învăț din 3 resure principale: [[https://teachyourselfcs.com/][Teach Yourself Computer Science]], [[https://github.com/ossu/computer-science][OSSU]] și [[https://functionalcs.github.io/curriculum/][functionalcs]]. Care e cea mai bună dintre ele - nu pot spune. Toate 3 sunt structurate ca o curiculă, de aceea calitatea lor depinde în mare parte de resursele pe care fiecare le recomandă.

La momentul scrierii, învăț din [[https://web.mit.edu/6.001/6.037/sicp.pdf][SICP]]. Pot să spun că ea "rupe mozgu" destul de bine, de asta eu încerc să o evit pe cât posibil, prin cursul [[https://www.coursera.org/learn/programming-languages][acesta]]. Din /functionalcs/ citesc doar câteva cărți (cele de OCaml și SML), dar nu citec tot, ci doar lucrurile pe care nu le știu (evident, sunt multe lucruri care se repetă în 3 curicule).

** Matematică
Aici am o grămadă de cărți. La momentul actual, învăț din /Basic Mathematics/ de Serge Lang și /Algebra/ de Gelfand. Ambele sunt cărți cu exerciții neobișnuite la care trebuie să te gândești. Ambele încep de la lucruri elementare, îți dau minimul de cunoștințe, și te pun să le aplici pe exerciții care necesită gândire. /Basic Mathematics/ include geometrie și trigonometrie, explicate, la fel, foarte succint. Nu necesită absolut nici o cunoștință matematică (poate doar tabla înmulțirii și să numeri până la 100).

Cel care a creat /functionalcs/ are și un /fel de două feluri/ pentru [[https://learnaifromscratch.github.io/math.html][matematică]]. Cartea pe care el o recomandă, însă, e mult prea jostkaia pentru mine. YMMV.

[[file:../../index.html][Înapoi]]
